# Generated by Django 3.0.8 on 2020-07-22 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('winner', models.ForeignKey(null=True,
                                             on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lose_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                              related_name='movekind_losto', to='game.MoveKind')),
                ('win_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                             related_name='movekind_winto', to='game.MoveKind')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='moves', to='game.Game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('move_kind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.MoveKind')),
            ],
        ),
    ]
